name: CDK Job

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  paths-filter
  first_job:
    runs-on: ubuntu-latest
   
    steps:
      - name: runs on changes 
        run: (ls)
