name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  check-cdk-changes:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.workflows }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          workflows:
            - 'cdk/**'

    - name: cdk changs
      if: steps.filter.outputs.workflows == 'true'
      run: echo "Workflow file"

    - name: not cdk changes
      if: steps.filter.outputs.workflows != 'true'
      run: echo "Workflow file"


