name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  check-cdk-changes:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.workflows }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          workflows:
            - 'cdk/**'

    - name: cdk changs
      if: steps.filter.outputs.workflows == 'true'
      run: echo "Workflow file"

    - name: not cdk changes
      if: steps.filter.outputs.workflows != 'true'
      run: echo "Workflow file"

next-jobs:
  call-cdk-job:
    uses: ./.github/workflows/cdk.yml
    with:
      ref: ${{ github.ref }}

  call-src-job:
    uses: ./.github/workflows/src.yml
    with:
      ref: ${{ github.ref }}

  call-deploy-job:
    needs: [call-cdk-job, call-src-job]

    uses: ./.github/workflows/src.yml
    with:
      ref: ${{ github.ref }}

