name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      cdk-modified: ${{ steps.filter.outputs.cdk-modified }}
      src-modified: ${{ steps.filter.outputs.src-modified }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          cdk-modified:
            - 'cdk/**'
          src-modified:
            - 'src/**'

    - name: cdk changs
      if: steps.filter.outputs.cdk-modified == 'true'

      run: echo "Workflow file"

    - name: not cdk changes
      if: steps.filter.outputs.cdk-modified != 'true'
      run: echo "Workflow file"

  call-cdk-job:
    needs: check-changes
    if: needs.check-changes.outputs.cdk-modified == 'true'
    uses: ./.github/workflows/cdk.yml
    with:
      ref: ${{ github.ref }}

  call-src-job:
    needs: check-changes
    if: needs.check-changes.outputs.src-modified == 'true'
    uses: ./.github/workflows/src.yml
    with:
      ref: ${{ github.ref }}
