name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-cdk-job:
    uses: ./.github/workflows/cdk.yml
    with:
      ref: ${{ gihub.ref }}

jobs:
  call-src-job:
    uses: ./.github/workflows/src.yml
    with:
      ref: ${{ gihub.ref }}

jobs:
  call-src-job:
    needs: [call-cdk-job, call-src-job]

    uses: ./.github/workflows/src.yml
    with:
      ref: ${{ gihub.ref }}

