name: SRC Job

on:
  workflow_call:
    inputs:
      ref:
        required: true


jobs:
  first_job:
    runs-on: ubuntu-latest
   
    steps:
      - name: always runs job
        run: (ls)
